# Run Shell script to create pet-clinic user , install java & tomcat 
- name: Transfer and execute a script.
  hosts: all
  tasks:
     - name: Copy and Execute the script 
       script: /home/gasser/ansible/tomcat.sh


# Add Admin user to Tomcat deployment manager
- name: Add user to Tomcat Manager
  hosts: all
  gather_facts: no
  become_user: pet-clinic  
  become_method: su 
  become: true

  
  vars:    
    tomcat_users_file_path: "/home/pet-clinic/apache-tomcat-10.1.11/conf/tomcat-users.xml"
    tomcat_manager_user: admin
    tomcat_manager_password: 123
  tasks:
    - debug:
        var: command_output.stdout_lines  
    - name: Add user to tomcat-users.xml
      lineinfile:
        path: "{{ tomcat_users_file_path }}"
        insertbefore: '</tomcat-users>'
        line: |
          <role rolename="manager-gui"/>
          <user username="{{ tomcat_manager_user }}" password="{{ tomcat_manager_password }}" roles="manager-gui"/>
        state: present
    - name: Tomcat on port 9090
      command: sed -i 's/<Connector port="8080"/<Connector port="9090"/' /home/pet-clinic/apache-tomcat-10.1.11/conf/server.xml

    - name: Restart tomcat
      command: /home/pet-clinic/apache-tomcat-10.1.11/bin/./shutdown.sh
      command: /home/pet-clinic/apache-tomcat-10.1.11/bin/./startup.sh



# Install Jenkins

- name: install jenkins
  hosts: all
  gather_facts: no
  become_user: pet-clinic  
  become_method: su 
  become: true
  become_flags: '--login'


  tasks: 
    - name: install jenkins
      get_url:
        url: https://get.jenkins.io/war-stable/2.401.2/jenkins.war
        dest: /home/pet-clinic
        mode: 0755
        checksum: sha256:86bd8e0b2b51075c99b00d43603c2858440bf011ecd089a5c791d0c964d40682
        group: pet-clinic
        owner: pet-clinic

# Run Jenkins
    - name: Run jenkins
      shell: java -jar /home/pet-clinic/jenkins.war --enable-future-java --httpPort=8090 > /dev/null 2>&1 &


# Task to copy the application build & sanity checks scripts to pet-clinic user and execute the build script

- name: Copy build script and run it on ansible user 
  hosts: all
  gather_facts: no
  become_user: pet-clinic  
  become_method: su 
  become: true
  become_flags: '--login'
  tasks:
    - name: Copy build script
      copy:
        src: /home/gasser/ansible/build.sh
        dest: /home/pet-clinic/build_directory
        owner: pet-clinic
        group: pet-clinic
        mode: '0755'
    - name: Copy Saint checks script 
        src: /home/gasser/ansible/sanitycheck.sh
        dest: /home/pet-clinic/build_directory
        owner: pet-clinic
        group: pet-clinic
        mode: '0755'
    - name: Execute the script
      shell: /home/pet-clinic/build_directory/./build.sh